### ISSUE TITLE
network-analysis-with-r tutorial 

### ISSUE THREAD

**Issue by elia427** [jessesadler/intro-to-r#1]
Hi,

Thanks for putting this useful tutorial https://www.jessesadler.com/post/network-analysis-with-r/. However, the following code is not working:
`routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)`

i get the following error

> Error in graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE) : 
  Some vertex names in edge list are not listed in vertex data frame

Thanks
Teshome

**Comment by jessesadler** [comment]
@teshu02 Glad that you have found the post useful. I think that the reason that you are getting the above error is because the "from" and "to" columns — the id columns for the edges — have to be the first two columns in data frame.

This is done with the following code: `edges <- select(edges, from, to, weight)`

Once the "from" and "to" columns are the first two columns, the code should work. Let me know if you are still having troubles.

**Comment by elia427** [comment]
@jessesadler Thank you so much.
